name: "Update Editor's Copy"

on:
  push:
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore
  pull_request:
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore

env:
  LANG: "en_US.UTF-8"

jobs:
  build:
    name: "Update Editor's Copy"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Cache Setup"
      id: cache-setup
      run: |
        mkdir -p "$HOME"/.cache/xml2rfc
        echo "::set-output name=path::$HOME/.cache/xml2rfc"
        date -u "+::set-output name=date::%FT%T"
    - name: "Cache References"
      uses: actions/cache@v3
      with:
        path: ${{ steps.cache-setup.outputs.path }}
        key: refcache-${{ steps.cache-setup.outputs.date }}
        restore-keys: |
          refcache-${{ steps.cache-setup.outputs.date }}
          refcache-
    - name: "Build Drafts"
      uses: martinthomson/i-d-template@v1m

    - name: "Update GitHub Pages"
      uses: martinthomson/i-d-template@v1m
      if: ${{ github.event_name == 'push' }}
      with:
        make: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: "Save HTML"
      uses: actions/upload-artifact@v3
      with:
        path: "*.html"

    - name: "Save Text"
      uses: actions/upload-artifact@v3
      with:
        path: "*.txt"

    - name: "Save XML"
      uses: actions/upload-artifact@v3
      with:
        path: "*.xml"
